DF <- read.csv("A191RL1Q225SBEA.csv")
class(DF)
typeof(DF)
str(DF)
if (!require("data.table")) install.packages("data.table")
library("data.table")
getDTthreads()
getDTthreads(verbose=TRUE)
setDTthreads(0)
getDTthreads()
class(DF)
typeof(DF)
str(DF)
names(DF)
ptm <- proc.time()
header <- read.table("A191RL1Q225SBEA.csv", header = TRUE,
                     sep=",", nrow = 1)
DF <- fread("A191RL1Q225SBEA.csv", skip=1, sep=",",
            header=FALSE, data.table=FALSE)
setnames(DF, colnames(header))
rm(header)
if (!require("readr")) install.packages("readr")
library("readr")
data.table::fread(DF)
